### ISSUE TITLE
ascii报错该怎么处理？

### ISSUE THREAD

**Issue by jwstaceyOvO** [lidalao/ServerStatus#4]
Traceback (most recent call last):
  File "_sss.py", line 249, in <module>
    cmd()
  File "_sss.py", line 213, in cmd
    print('- - - \u6b22\u8fce\u4f7f\u7528\u6700\u7b80\u6d01\u7684\u63a2\u9488: Server Status - - -')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-15: ordinal not in range(128)
CentOS 7，小鸡是日本的，可能和这个有关

**Comment by lidalao** [comment]
编码问题，下一版处理

**Comment by jerry8601lz** [comment]
我安装完了之后报错
